export const bannerChara = {
  seele: "assets/banner/Seele.webp",
  silverWolf: "assets/banner/Silver Wolf.webp",
  blade: "assets/banner/Blade.webp",
  kafka: "assets/banner/Kafka.webp",
  fuXuan: "assets/banner/Fu Xuan.webp",
  jingliu: "assets/banner/Jingliu.webp",
  topaz: "assets/banner/Topaz.webp",
  huohuo: "assets/banner/Huohuo.webp",
  argenti: "assets/banner/Argenti.webp",
  ruanMei: "assets/banner/Ruan Mei.webp",
  drRatio: "assets/banner/Dr. Ratio.webp",
  blackSwan: "assets/banner/Black Swan.webp",
  sparkle: "assets/banner/Sparkle.webp",
  acheron: "assets/banner/Acheron.webp",
  robin: "assets/banner/Robin.webp",
};

export const iconChara = {
  seele: "assets/icon/characters/Seele.webp",
  silverWolf: "assets/icon/characters/Silver Wolf.webp",
  blade: "assets/icon/characters/Blade.webp",
  kafka: "assets/icon/characters/Kafka.webp",
  fuXuan: "assets/icon/characters/Fu Xuan.webp",
  jingliu: "assets/icon/characters/Jingliu.webp",
  topaz: "assets/icon/characters/Topaz.webp",
  huohuo: "assets/icon/characters/Huohuo.webp",
  argenti: "assets/icon/characters/Argenti.webp",
  ruanMei: "assets/icon/characters/Ruan Mei.webp",
  drRatio: "assets/icon/characters/Dr. Ratio.webp",
  blackSwan: "assets/icon/characters/Black Swan.webp",
  sparkle: "assets/icon/characters/Sparkle.webp",
  acheron: "assets/icon/characters/Acheron.webp",
  robin: "assets/icon/characters/Robin.webp",
};

export const karakter = {
  seele: "assets/characters/Seele Splash Art.webp",
  silverWolf: "assets/characters/Silver Wolf Splash Art.webp",
  blade: "assets/characters/Blade Splash Art.webp",
  kafka: "assets/characters/Kafka Splash Art.webp",
  fuXuan: "assets/characters/Fu Xuan Splash Art.webp",
  jingliu: "assets/characters/Jingliu Splash Art.webp",
  topaz: "assets/characters/Topaz and Numby Splash Art.webp",
  huohuo: "assets/characters/Huohuo Splash Art.webp",
  argenti: "assets/characters/Argenti Splash Art.webp",
  ruanMei: "assets/characters/Ruan Mei Splash Art.webp",
  drRatio: "assets/characters/Dr. Ratio Splash Art.webp",
  blackSwan: "assets/characters/Black Swan Splash Art.webp", 
  sparkle: "assets/characters/Sparkle Splash Art.webp", 
  acheron: "assets/characters/Acheron Splash Art.webp", 
  robin: "assets/characters/Robin Splash Art.webp", 
  clara: "assets/characters/Clara Splash Art.webp",
  bailu: "assets/characters/Bailu Splash Art.webp",
  hook: "assets/characters/Hook Splash Art.webp",
  guinaifen: "assets/characters/Guinaifen Splash Art.webp",
};